global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'localhost:9100' ] # if installed on same host - change if remote

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'BACKEND_HOST:3000' ] # REPLACE BACKEND_HOST with your EC2 public IP or DNS
